### PR TITLE
Highlighting "1" in action rolls

### LINKED ISSUE #282: Add color coding to action rolls results
It's easier/faster than reading the result's text.

The badges you can find in roll20 sheet can be an example:

image

### LINKED ISSUE #285: Highlight a score of 1 on an action die
Some assets react to a score of 1 on an action die on some rolls, e.g. _Totem: If you roll a 1 on your action die when using a companion ability, the magic is spent._
It might be useful to highlight this occurrence, either always, or even better, if the character has this kind of asset.

### PR DESCRIPTION
**Pull request by Meathox**
Closes #285 
Closes #282 

I added the `theme.palette.warning.light` color to the `roll.action` result whent it's a 1 and added a text saying "Natural 1" under the `actionResultLabel` (same kind as the "Doubles" one).

If you'd like something different, say it and I"ll change ;)

### CODE REVIEW

**Comment by scottbenton** [comment]
I like it! The "Natural 1" text is a great addition I hadn't considered.
The only thing I'm not sold on is the styling for the "1" - not sure if the warning color is sufficient or if going for the error color is better. What do you think of these? 

image

image

**Comment by Meathox** [comment]
> I like it! The "Natural 1" text is a great addition I hadn't considered. The only thing I'm not sold on is the styling for the "1" - not sure if the warning color is sufficient or if going for the error color is better. What do you think of these?
> 
> image
> 
> image

Oh that's nice! I'll try the one with the border. I though about underlining the 1 but wasn't really fond of the result when I tried.

**Comment by Meathox** [comment]
Changed it ! I also changed the color to pick the theme.primary.light. I think it looks better than a regular warning or error.

image
image

**Comment by scottbenton** [comment]
Great choice!

**Pull request merged**
