### PR TITLE
Added hooks for searching and move filtering. Implemented search field in MovesSection

### LINKED ISSUE #7: Add search bar to Moves list
There are a lot of moves, so being able to quickly find the right one would help the flow of the game. Adding a search bar to the top of the section to filter using .contains on the move label would be a big help. If the search bar contains text, a button to clear it would be useful.

### PR DESCRIPTION
**Pull request by fracergu**
closes #7

### CODE REVIEW

**Review by scottbenton — APPROVED** [review]
This looks great - thank you for the contribution! I'm new to open-source collaboration via github - is there anything I can do to make collaboration on this repo easier for you & others?

**Comment by fracergu** [comment]
Hi Scott! Glad you like it!

I really don't have much to add, the project seems very well structured and it is very user friendly to start it up and start working with it.

Maybe it would be a good idea to add a little more information about how to configure the Firebase environment (how to create the application in the Google Console, set up the database, get the API keys, etc.), it's been a while since I worked with it and the reality is that it took me a while.

**Comment by scottbenton** [comment]
I can for sure add more information on how to set that up. That's good feedback. If you have any improvements or suggestions on how to improve anything feel free to open up an issue or submit a PR! I'm currently working on getting the preview environment set up properly for forked PRs, so once I get that figured out I will merge this in.

**Comment by fracergu** [comment]
Sure!
We are participating right now in an Open Source development jam and it's been hell finding projects to collaborate with because they have little or no documentation on how to set up the project to start working with it, and we think it's a critical point, since the simpler it is, the more likely it is that someone will collaborate.

We will be during the next hours reviewing your project among others, so don't doubt that if we have any improvement, we will include it 😀

**Pull request merged**
